#pragma once

#include <algorithm>
#include <cangine/cangine.hpp>
#include <cangine/engine/components/component.hpp>
#include <cangine/engine/components/quadrenderer_component.hpp>
#include <cangine/engine/components/textrenderer_component.hpp>
#include <cangine/engine/components/transform_component.hpp>
#include <cangine/engine/gameobjects/game_object.hpp>
#include <cangine/engine/gameobjects/ui/label_object.hpp>
#include <cangine/platform/input.hpp>
#include <cangine/platform/mouse.hpp>
#include <cangine/shapes/rectangle.hpp>
#include <cangine/types/vector2.hpp>
#include <cangine/types/vector3.hpp>
#include <cangine/util/color.hpp>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <functional>
#include <iostream>
#include <string>
#include <vector>